name: CI (smoke)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  smoke:
    name: Node install check (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (lock-aware)
        shell: bash
        run: |
          if [ -f package-lock.json ]; then
            echo "Using npm ci";
            npm ci
          else
            echo "No package-lock.json, using npm install";
            npm install --no-audit --no-fund
          fi

      - name: Print versions and list files
        shell: bash
        run: |
          node -v
          npm -v
          ls -la
