name: Build Release Artifacts

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            build_cmd: npm run dist:win
          - os: ubuntu-latest
            build_cmd: npm run dist:linux
          - os: macos-latest
            build_cmd: npm run dist:mac

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: ${{ matrix.build_cmd }}

      - name: Repack (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          if (Test-Path 'dist/Kage-win-x64.zip') { Remove-Item -Force 'dist/Kage-win-x64.zip' }
          Compress-Archive -Path 'dist/win-unpacked/*' -DestinationPath 'dist/Kage-win-x64.zip' -Force

      - name: Repack (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          rm -f dist/Kage-linux-x64.tar.gz
          tar -C dist/linux-unpacked -czf dist/Kage-linux-x64.tar.gz .

      - name: Repack (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          rm -f dist/Kage-mac-arm64.zip
          APP_PATH=$(echo dist/mac*/Kage.app)
          ditto -c -k --sequesterRsrc --keepParent "$APP_PATH" "dist/Kage-mac-arm64.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kage-${{ runner.os }}
          path: |
            dist/*.zip
            dist/*.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            artifacts/**/**/*.zip
            artifacts/**/**/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
